"""indices_performance_y_timestamps_auditoria

Revision ID: a44c260c7bf6
Revises: b1b681b3a2a7
Create Date: 2026-09-12 21:07:30.280714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44c260c7bf6'
down_revision: Union[str, Sequence[str], None] = 'b1b681b3a2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Columnas de timestamp existentes que antes usaban `default=` de Python (se llenaban
    # solo si la inserción pasaba por el ORM) y ahora usan `server_default=func.now()` en el
    # modelo — autogenerate no detecta este cambio en columnas ya existentes (no hay
    # `compare_server_default=True` en alembic/env.py), así que se agrega a mano.
    op.alter_column('usuarios', 'fecha_creacion', server_default=sa.text('now()'))
    op.alter_column('usuarios', 'actualizado_en', server_default=sa.text('now()'))
    op.alter_column('citas', 'creada_en', server_default=sa.text('now()'))
    op.alter_column('magic_links', 'fecha_creacion', server_default=sa.text('now()'))
    op.alter_column('descuento_usos', 'fecha_canje', server_default=sa.text('now()'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categorias', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_cita_servicios_cita_id', 'cita_servicios', ['cita_id'], unique=False)
    op.create_index('ix_cita_servicios_servicio_id', 'cita_servicios', ['servicio_id'], unique=False)
    op.add_column('citas', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_citas_cliente_programada', 'citas', ['cliente_id', 'programada_en'], unique=False)
    op.create_index('ix_citas_personal_programada', 'citas', ['personal_id', 'programada_en'], unique=False)
    op.add_column('clientes', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clientes', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_descuento_usos_cita_id', 'descuento_usos', ['cita_id'], unique=False)
    op.create_index('ix_descuento_usos_cliente_id', 'descuento_usos', ['cliente_id'], unique=False)
    op.create_index('ix_descuento_usos_reto_origen_id', 'descuento_usos', ['reto_origen_id'], unique=False)
    op.add_column('descuentos', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('descuentos', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('disponibilidad_personal', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('disponibilidad_personal', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_disponibilidad_personal_personal_id', 'disponibilidad_personal', ['personal_id'], unique=False)
    op.add_column('fichas_salud', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fichas_salud', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_fichas_salud_cliente_id', 'fichas_salud', ['cliente_id'], unique=False)
    op.create_index('ix_magic_links_usuario_id', 'magic_links', ['usuario_id'], unique=False)
    op.add_column('pagos', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pagos', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_pagos_cita_id', 'pagos', ['cita_id'], unique=False)
    op.create_index('ix_pagos_cliente_id', 'pagos', ['cliente_id'], unique=False)
    op.create_index('ix_pagos_confirmado_por', 'pagos', ['confirmado_por'], unique=False)
    op.add_column('personal', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('personal', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('retos', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('retos', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('servicios', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('servicios', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_servicios_categoria_id', 'servicios', ['categoria_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_servicios_categoria_id', table_name='servicios')
    op.drop_column('servicios', 'actualizado_en')
    op.drop_column('servicios', 'creado_en')
    op.drop_column('retos', 'actualizado_en')
    op.drop_column('retos', 'creado_en')
    op.drop_column('personal', 'actualizado_en')
    op.drop_column('personal', 'creado_en')
    op.drop_index('ix_pagos_confirmado_por', table_name='pagos')
    op.drop_index('ix_pagos_cliente_id', table_name='pagos')
    op.drop_index('ix_pagos_cita_id', table_name='pagos')
    op.drop_column('pagos', 'actualizado_en')
    op.drop_column('pagos', 'creado_en')
    op.drop_index('ix_magic_links_usuario_id', table_name='magic_links')
    op.drop_index('ix_fichas_salud_cliente_id', table_name='fichas_salud')
    op.drop_column('fichas_salud', 'actualizado_en')
    op.drop_column('fichas_salud', 'creado_en')
    op.drop_index('ix_disponibilidad_personal_personal_id', table_name='disponibilidad_personal')
    op.drop_column('disponibilidad_personal', 'actualizado_en')
    op.drop_column('disponibilidad_personal', 'creado_en')
    op.drop_column('descuentos', 'actualizado_en')
    op.drop_column('descuentos', 'creado_en')
    op.drop_index('ix_descuento_usos_reto_origen_id', table_name='descuento_usos')
    op.drop_index('ix_descuento_usos_cliente_id', table_name='descuento_usos')
    op.drop_index('ix_descuento_usos_cita_id', table_name='descuento_usos')
    op.drop_column('clientes', 'actualizado_en')
    op.drop_column('clientes', 'creado_en')
    op.drop_index('ix_citas_personal_programada', table_name='citas')
    op.drop_index('ix_citas_cliente_programada', table_name='citas')
    op.drop_column('citas', 'actualizado_en')
    op.drop_index('ix_cita_servicios_servicio_id', table_name='cita_servicios')
    op.drop_index('ix_cita_servicios_cita_id', table_name='cita_servicios')
    op.drop_column('categorias', 'actualizado_en')
    op.drop_column('categorias', 'creado_en')
    # ### end Alembic commands ###

    op.alter_column('descuento_usos', 'fecha_canje', server_default=None)
    op.alter_column('magic_links', 'fecha_creacion', server_default=None)
    op.alter_column('citas', 'creada_en', server_default=None)
    op.alter_column('usuarios', 'actualizado_en', server_default=None)
    op.alter_column('usuarios', 'fecha_creacion', server_default=None)
