"""esquema inicial

Revision ID: b1b681b3a2a7
Revises: 
Create Date: 2026-08-31 21:01:53.530649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1b681b3a2a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono_url', sa.String(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=False),
    sa.Column('orden_visualizacion', sa.Integer(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_categorias_nombre')
    )
    op.create_table('descuentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('porcentaje', 'monto_fijo', name='tipo_descuento', native_enum=False), nullable=False),
    sa.Column('scope', sa.Enum('publico', 'privado', 'reto', name='scope_descuento', native_enum=False), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('monto_minimo', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('max_usos_global', sa.Integer(), nullable=True),
    sa.Column('max_usos_por_cliente', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_descuentos_codigo', 'descuentos', ['codigo'], unique=True, postgresql_where=sa.text('codigo IS NOT NULL'))
    op.create_table('retos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion_visible', sa.Text(), nullable=False),
    sa.Column('visitas_requeridas', sa.Integer(), nullable=False),
    sa.Column('dias_ventana', sa.Integer(), nullable=False),
    sa.Column('recompensa_tipo', sa.Enum('descuento', 'servicio_gratis', 'credito', name='recompensa_tipo', native_enum=False), nullable=False),
    sa.Column('recompensa_valor', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('correo_verificado', sa.Boolean(), nullable=False),
    sa.Column('rol', sa.Enum('cliente', 'trabajador', 'admin', name='rol_usuario', native_enum=False), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('foto_perfil_url', sa.String(), nullable=True),
    sa.Column('acepta_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_usuarios_correo', 'usuarios', ['correo'], unique=True, postgresql_where=sa.text('correo IS NOT NULL'))
    op.create_index('ux_usuarios_telefono', 'usuarios', ['telefono'], unique=True, postgresql_where=sa.text('telefono IS NOT NULL'))
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('canal_captacion', sa.String(), nullable=True),
    sa.Column('etiquetas', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('esta_bloqueada', sa.Boolean(), nullable=False),
    sa.Column('motivo_bloqueo', sa.Text(), nullable=True),
    sa.Column('fecha_bloqueo', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', name='uq_clientes_usuario_id')
    )
    op.create_table('magic_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_magic_links_token', 'magic_links', ['token'], unique=True)
    op.create_table('personal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('color_agenda', sa.String(), nullable=False),
    sa.Column('comision_porcentaje', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('tipo_contrato', sa.Enum('planilla', 'honorarios', name='tipo_contrato', native_enum=False), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', name='uq_personal_usuario_id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion_tecnica', sa.Text(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('monto_deposito', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('requiere_ficha_salud', sa.Boolean(), nullable=False),
    sa.Column('horas_cancelacion_sin_penalidad', sa.Integer(), nullable=False),
    sa.Column('imagen_referencia_url', sa.String(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('personal_id', sa.UUID(), nullable=False),
    sa.Column('programada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('termina_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmada', 'en_curso', 'completada', 'cancelada', 'cancelada_tardia', 'no_show', name='estado_cita', native_enum=False), nullable=False),
    sa.Column('hora_llegada_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('notas_especialista', sa.Text(), nullable=True),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('penalizacion_aplicada', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidad_personal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personal_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('minutos_buffer', sa.Integer(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fichas_salud',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tipo_restriccion', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('severidad', sa.Enum('informativa', 'moderada', 'critica', name='severidad_ficha', native_enum=False), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cita_servicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('servicio_id', sa.UUID(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descuento_usos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('descuento_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('reto_origen_id', sa.UUID(), nullable=True),
    sa.Column('fecha_canje', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['descuento_id'], ['descuentos.id'], ),
    sa.ForeignKeyConstraint(['reto_origen_id'], ['retos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descuento_id', 'cliente_id', 'cita_id', name='uq_descuento_uso_cliente_cita')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('deposito', 'saldo', 'total', 'penalizacion', 'reembolso', name='tipo_pago', native_enum=False), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'yape', 'plin', 'tarjeta', name='metodo_pago', native_enum=False), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmado', 'rechazado', 'reembolsado', name='estado_pago', native_enum=False), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('referencia_externa', sa.String(), nullable=True),
    sa.Column('comprobante_url', sa.String(), nullable=True),
    sa.Column('confirmado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nota_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['confirmado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('descuento_usos')
    op.drop_table('cita_servicios')
    op.drop_table('fichas_salud')
    op.drop_table('disponibilidad_personal')
    op.drop_table('citas')
    op.drop_table('servicios')
    op.drop_table('personal')
    op.drop_index('ux_magic_links_token', table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_table('clientes')
    op.drop_index('ux_usuarios_telefono', table_name='usuarios', postgresql_where=sa.text('telefono IS NOT NULL'))
    op.drop_index('ux_usuarios_correo', table_name='usuarios', postgresql_where=sa.text('correo IS NOT NULL'))
    op.drop_table('usuarios')
    op.drop_table('retos')
    op.drop_index('ux_descuentos_codigo', table_name='descuentos', postgresql_where=sa.text('codigo IS NOT NULL'))
    op.drop_table('descuentos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
